# Referencia na formatação
hoje = Time.now

puts "Meses".center(20, "-")
# %b - Abreviação do nome do mês (jan)
puts hoje.strftime("%b")
# %B - Nome completo do mês (janeiro)
puts hoje.strftime("%B")
# %d - Dia do mês (01)
puts hoje.strftime("%d")
# %m - Mês (01..12)
puts hoje.strftime("%m")

puts "Dias".center(20, "-")
# %j - Dia do ano (001..366)
puts hoje.strftime("%j")
# %w - Dia da semana (0..6)
puts hoje.strftime("%w")
# %A - Dia da semana (domingo)
puts hoje.strftime("%A")
# %a - Dia da semana (dom)
puts hoje.strftime("%a")
# %u - Dia da semana (7)
puts hoje.strftime("%u")
# %W - Semana do ano (00..53)
puts hoje.strftime("%W")
# %e - Dia do mês (1..31)
puts hoje.strftime("%e")

puts "Datas".center(20, "-")
# %x - Data (DD/MM/AAAA)
puts hoje.strftime("%x")
# %c - Data e hora (seg jan 1 00:00:00 2007)
puts hoje.strftime("%c")
# %D - Data (MM/DD/AAAA)
puts hoje.strftime("%D")
# %F - Data (AAAA-MM-DD)
puts hoje.strftime("%F")
# %v - Data (DD-MMM-AAAA)
puts hoje.strftime("%v")
# %x - Data (DD/MM/AAAA)
puts hoje.strftime("%x")

puts "Horas".center(20, "-")
# %X - Hora (HH:MM:SS)
puts hoje.strftime("%X")
# %H - Hora (00..23)
puts hoje.strftime("%H")
# %I - Hora (00..12)
puts hoje.strftime("%I")
# %p - AM ou PM
puts hoje.strftime("%p")
# %T - Hora (HH:MM:SS)
puts hoje.strftime("%T")
# %r - Hora (HH:MM:SS AM ou PM)
puts hoje.strftime("%r")
# %R - Hora (HH:MM)
puts hoje.strftime("%R")
# %X - Hora (HH:MM:SS)
puts hoje.strftime("%X")
# %Z - Fuso horário
puts hoje.strftime("%Z")
# %M - Minutos (00..59)
puts hoje.strftime("%M")
# %S - Segundos (00..59)
puts hoje.strftime("%S")

puts "Anos".center(20, "-")
# %y - Ano (00..99)
puts hoje.strftime("%y")
# %Y - Ano (AAAA)
puts hoje.strftime("%Y")
# %Y - Ano (AAAA)
puts hoje.strftime("%Y")
